config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  

  resources "categories" do
    resources "books"
  end  

  resources "users" do
    resources "books" do
      member do
         patch "book_return"
      end
    end  
  end

  resources "books" 
  

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	validates :title, presence: true
	validates :category_id, presence:true
	validates :category_id, numericality: true, unless: "category_id.blank?"
	validates :description, presence: true
	validates :description, length: {minimum: 10}, unless: "description.blank?"

	belongs_to :category 
	has_many :user_books
	has_many :users, through: :user_books
	#scope :created_before, ->(time) { where("created_at < ?", time) }
	#scope :published_last_week, -> { where('created_at <= ?', 1.week.ago) }
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true
	validates :name,length: { minimum: 2 }, format: { with: /\A[a-zA-Z]+\Z/, message: "Only allows letters....." }, unless: "name.blank?"
	has_many :books, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
	
  validates :name, presence: true
  validates :name, length: { minimum: 2 }, format: { with: /\A[a-zA-Z]+\Z/, message: "Only allows letters....." }, unless: "name.blank?" 	 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :user_books      
   has_many :books, through: :user_books
end

app/models/user_book.rb
class UserBook < ActiveRecord::Base
	belongs_to :user
	belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	#layout :append_layout
	before_action :authenticate_user!, except: [:index]
	before_action :find_user, except: [:index]
	before_action :find_book, only: [ :book_return, :show, :edit, :update, :destroy] 
	before_action :find_categories_array, only: [:new, :edit]

	def index 
		#render file: "/home/sahu/my_rails_work/MessageBoard/app/views/messages/index"
		@books = Book.page(params[:page]).per(5)
		#raise @books.inspect
		@book = Book.new
		#(Not Working)render js: "alert('Hello Rails');"
		#render xml: @books
		#render json: @books
		#render plain: "OK" 
		#render inline: "<% @books.each do |b| %><p><%= b.title %></p><% end %>"
		@user = current_user
		#(Didn't find any use)render status: 500
		#render status: :forbidden
		#render layout: false
		#(Not working)render xml: photo, location: photo_url("/home/sahu/background1.jpeg")
	end

	def show
		@books = Book.all
		#respond_to do |format|
		#	format.html
		#	format.json{ render json: @book.as_json( only: [:id, :title] )}
	#	end
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		if @book.save
			@books = Book.all
		else
			@categories_array = Category.pluck(:name, :id)
			render "new"
		end	
	end

	def edit
	end

	def update
	# raise params.inspect	
	   @category = @book.category
		if params[:user_id] == nil
			#if
			 @book.update(book_params)

			#	redirect_to books_path
			#else
			#	render "edit"
			#end
		else
			user = params[:user_id]
			user_book = @book.user_books.new(user_id: user)
			present_available_books = @book.present_available_books
			#raise book_count.inspect
			if user_book.save && @book.update(present_available_books: present_available_books-1)
			 #@books = Book.all
				#redirect_to category_path(@category)
				redirect_to :back
			end
		end		
	end

	

	def destroy
		#if
		 @book.destroy

			redirect_to books_path
		#end	
	end

	def book_return
		user_id = params[:user_id] 
		user_book_id = UserBook.find_by(book_id: @book, user_id: user_id)
			#raise @user_book_id.inspect
		if user_book_id.destroy
			redirect_to books_path
		end
	end

	private

	def find_book
		@book = Book.find(params[:id])
	end

	def book_params
		params.require(:book).permit(:title, :description, :category_id) 
	end

	def find_categories_array
		@categories_array = Category.pluck(:name, :id) 
	end

	def find_category
		@category = Category.find(params[:category_id])
	end

	def find_user
		@user = current_user
	end

	def append_layout
		if user_signed_in?
			if current_user == "admin"
				layout "admin"
			else
				layout "user"
			end		
		end	
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index]		
  before_action :find_category, only: [:show, :edit, :destroy, :update] 
  before_action :find_user, except: [:index]

  def index
  	@categories = Category.page(params[:page]).per(5)
    @user = current_user
  end

  def show
    @category_books = @category.books.page(params[:page]).per(5)
  end

  def new
  	@category = Category.new
  end

  def create
  	 @category = Category.new(category_params)
  	if @category.save
  		redirect_to categories_path
  	else
  		render "new"	
  	end
  end

  def edit
  end

  def update
  	 if @category.update(category_params)
  	 	redirect_to categories_path
  	else
  		render "edit"	
  	 end
  end

  def destroy
  	if @category.destroy
  		redirect_to categories_path
  	end
  end

  private

  def find_category
  	@category = Category.find(params[:id])
  end

  def category_params
  	params.require(:category).permit(:name)
  end

  def find_user
		@user = current_user
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/user_books_controller.rb
class UserBooksController < ApplicationController


	def update
		raise params.inspect
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
  	@book = Book.find(params[:book_id])
  	user = current_user
  	user_book = Book.new(user_id :user)
  	if user_book.save
  		flash[:success] = "Book successfully booked"
  		redirect_to category_book_path(@book)
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/user_books_helper.rb
module UserBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books.html.erb
<div class="container text-center">	
<% if user_signed_in? %>
	<% if @user.books.count > 4 %>
		<% if @user.role != "admin" %>
			<b class="alert " style="color:red">To take another book, you have to submit already taken books.</b>
		<% end %>
	<% end %>
<% end %>			
</div>
<h2>Available Books 
		<% if user_signed_in? %>
			<% if @user.role == "admin" %>
				<%= link_to "Create Book", new_book_path, class: "btn btn-success pull-right", remote: true %>	
			<% end %>	
		<% end %>	
	</h2><hr/>
	<div class="col-md-8 col-md-offset-2">	
		<table class="table borderless">
			<tr>
				<b><th class="sno">S.no</th>
					<th>Title</th>
					<th>Category</th>
					<% if user_signed_in? %>
						<% if @user.role != "admin" %>
							<% if @user.books.count <= 4 %>
								<th>Status</th>
							<% end %>	
						<% else %>
							<th>Available Books</th>	
						<% end %>
					<% end %>		
				</b>
			</tr>
			<% @books.each_with_index do |book,i| %>	
				<tr>
					<td class="sno"><%= i+1 %>.</td>	
					<td><%= link_to book.title, book_path(book) %></td>
					<td><%= link_to book.category.name, category_path(book.category)%></td>
						<% if user_signed_in? %>
							<% if @user.books.count <= 4 %>
							<td>
								<% if @user.role != "admin" %>
									<% if book.present_available_books > 0  %>
										<% if book.user_books.where(user_id: @user.id).present? %>
											<%= link_to "Booked", books_path, class: "btn btn-danger pull-right"  %>
										<% else %>	
											<%= link_to "Add Book", user_book_path(@user,book), method: :put, class: "btn btn-success pull-right"  %>
										<% end %>
									<% else %>
										<%= link_to "Booked", books_path, class: "btn btn-danger pull-right"  %>
									<% end %>						
								<% else %>
									<%= book.present_available_books %>/<%= book.book_count %>	
								<% end %>
							</td>
							<% end %>	
						<% end %>
				</tr>
			<% end %>		
		</table>
	</div>

app/views/books/_edit.html.erb
<div class="container">
	<h2>Adding Book <%= link_to "Back", book_path(@book), class: "btn btn-success pull-right" %></h2><hr/>
	<div class="col-md-8 col-md-offset-2">
		<%= render "form" %>
	</div>
</div>

app/views/books/_form.html.erb
<h2 class="text-center">Create Book</h2><hr/>
	<%= form_for(@book, remote: true) do |f|%>
	<% if @book.errors.any? %>
		<h3 class="errors"><%= pluralize(@book.errors.count, "error") %> prohibited this company from being saved:</h3>
		<ul class="errors">
			<% @book.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
	<div class="col-md-9 col-md-offset-1">
		<div class="form-group">
			<p><b>Title:</b></p>
			<%= f.text_field :title, class: "form-control" %>
		</div>
		<div class="form-group">
			<p><b>Description:</b></p>
			<%= f.text_area :description, class: "form-control" %>
		</div>	
		<div class="form-group">
			<p><b>Category</b></p>
			<%= f.select(:category_id, options_for_select(@categories_array), {}, { class: "form-control" }) %>	
			<%# options_from_collection_for_select(Category.all, :id, :name) %>
		</div>
		<div class="form-group">
				<%= f.submit :class => "btn btn-success" %>
		</div>	
	</div>
<% end %>

app/views/books/_new.html.erb
<div class="container">
	<h2>Adding Book 
		<%= link_to "Categories", categories_path, class: "btn btn-success pull-right" %>
		<%= link_to "books", books_path, class: "btn btn-success pull-right" %>
	</h2><hr/>
	<div class="col-md-8 col-md-offset-2">
		<%= render "books/form" %>
	</div>
</div>

app/views/books/_show_book.html.erb
<h2 class="text-center" ><%= @book.title %></h2><hr/>
		<p><h3><u>Description:</u></h3></p>
		<p class="description"><%= @book.description %></p>

app/views/books/create.js.erb
$("#books").html("<%= escape_javascript(render("books/books")) %>");
$("#create_book").html("");

app/views/books/destroy.js.erb
$("#")

app/views/books/edit.html.erb
<div class="container">
	<h2>Adding Book <%= link_to "Back", book_path(@book), class: "btn btn-success pull-right" %></h2><hr/>
	<div class="col-md-8 col-md-offset-2">
		<%= render "form" %>
	</div>
</div>

app/views/books/edit.js.erb
$("#show-book").hide();
$("#edit-book").show();
$("#edit-book").html("<%= escape_javascript(render("edit")) %>");

app/views/books/index.html.erb
<div class="container container1">
<div class="container">
	<div id="create_book">
	</div>
</div>	
<div class="container" id="books">
	<%= render "books/books" %>
</div>
<div class="container text-center">
	<hr/>	<%= paginate @books %><hr/>
</div>		
<div>
	<% if user_signed_in? %>	
		<h2 class="text-center">Taken Books</h2><hr/>	
		<div class="col-md-8 col-md-offset-2">
			<table class="table borderless">
				<tr>
					<b>
						<th class="sno">S.no</th>
						<th>Book title</th>
						<th>Booked Date</th>
						<% if @user.role == "admin" %>
							<th>User</th>
							<th>Action</th>
						<% end %>
					</b>	
				</tr>	
				<% if @user.role == " " %>	
					<% @user.books.each_with_index do |user_book, i| %>
						<tr>
							<td class="sno"><%= i+1 %>.</td>
							<td class="user_books"><%= user_book.title %></td>
							<td class="user_books"><%= user_book.updated_at.strftime("%d-%B-%Y") %></td>
						</tr>	
					<% end %>
				<% else %>	
					<% @books.each_with_index do |book,i| %>
						<% if book.users.present? %>
							<tr>
								<td class="sno"><%= i+1 %>.</td>
								<td class="user_books"><%= book.title %></td>
								<td class="user_books"><%= book.updated_at.strftime("%d-%B-%Y") %></td>
								<% book.users.each do |user| %>
									<td class="user_books">
										<%= user.name %>
									</td>
									<td>
										<%= link_to "Return Book", book_return_user_book_path(user,book), method: :patch, class: "btn btn-success pull-right" %>
									</td>
								<% end %>
							</tr>	
						<% end %>		
					<% end %>
				<% end %>	
			</table>		
		</div>	
	<% end %>	
</div>	
</div>

app/views/books/new.html.erb
<div class="container">
	<h2>Adding Book 
		<%= link_to "Categories", categories_path, class: "btn btn-success pull-right" %>
		<%= link_to "books", books_path, class: "btn btn-success pull-right" %>
	</h2><hr/>
	<div class="col-md-8 col-md-offset-2">
		<%= render "books/form" %>
	</div>
</div>

app/views/books/new.js.erb
/*$("#create_book-main-div").show();*/
$("#create_book").html("<%= escape_javascript(render("books/new")) %>");

app/views/books/show.html.erb
<div class="container container1">
	<div class="container text-center">	
	<% if user_signed_in? %>
		<% if @user.books.count > 4 %>
			<% if @user.role != "admin" %>
				<b class="alert " style="color:red">To take another book, you have to submit already taken books.</b>
			<% end %>
		<% end %>
	<% end %>			
	</div>
	<div class="container">
		<h2> Show Page 
			<%= link_to "Back", books_path, class: "btn btn-success pull-right" %>
			<% if user_signed_in? %>
				<% if @user.role == "admin" %>
					<%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: " Are you sure want to delete? " }, class: "btn btn-success pull-right" %>
					<%= link_to "Edit", edit_book_path(@book), class: "btn btn-success pull-right", remote: true %>
				<% else %>
					<% if @user.books.count <= 4 %>
						<% if @book.users.present? %>
							<%= link_to "Booked", books_path, class: "btn btn-danger pull-right"  %>
						<% else %>	
						  <%= link_to "Add Book", user_books_path(@user), method: :patch, class: "btn btn-success pull-right"  %>
						<% end %>
					<% end %>	
				<% end %>
			<% end %>		
		</h2><hr/>
		<div id="edit-book">	
		</div>
		<ul class="pager">
			<% if @books.first.id < @book.id %>
				<li class="previous"><%= link_to "Previous", book_path(@books.where("id < ?", @book).last) %></li>
			<% else %>	
				<li class="previous disabled"><%= link_to "Previous" %></li>
			<% end %>
			<% if  @books.last.id > @book.id %>	
				<li class="next"><%= link_to "Next",book_path(@books.where("id > ?", @book).first) %></li>
			<% else %>	
				<li class="next disabled"><%= link_to "Next" %></li>
			<% end %>	
		</ul>	
		<div class="col-md-8 col-md-offset-2" id="show-book">
			<%= render "books/show_book" %>
		</div>
	</div>	
</div>

app/views/books/update.js.erb
$("#edit-book").hide();
$("#show-book").show();
$("#show-book").html("<%= escape_javascript(render("books/show_book")) %> ");

app/views/categories/_form.html.erb
<h2 class="text-center">Create Category</h2><hr/>
<%= form_for @category do |f|%>
	<% if @category.errors.any? %>
		<h3 class="errors"><%= pluralize(@category.errors.count, "error") %> prohibited this company from being saved:</h2>
		<ul class="errors">
			<% @category.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
	<div class="col-md-9 col-md-offset-1">
		<div class="form-group">
			<p><b>Name:</b></p>
			<%= f.text_field :name, class: "form-control" %>
		</div>	
		<div class="form-group">
				<%= f.submit :class => "btn btn-success" %>
		</div>	
	</div>
<% end %>

app/views/categories/edit.html.erb
<div class="container container1">	
	<div class="container">
		<h2>Adding Book <%= link_to "Back", category_path(@category), class: "btn btn-success pull-right" %></h2><hr/>
		<div class="col-md-8 col-md-offset-2">
			<%= render "categories/form" %>
		</div>
	</div>
</div>	

app/views/categories/index.html.erb
<div class="container container1">
	<div id="create_book">
	</div>
	<div class="container">
		<h2>Available Categories
			<% if user_signed_in? %>
				<% if @user.role == "admin" %>
					<%= link_to "Add Category", new_category_path, class: "btn btn-success pull-right" %>
					<%# link_to "Create Book", new_book_path, class: "btn btn-success pull-right" %>
				<% end %>
			<% end %>		
			<%= link_to "Available Books", books_path, class: "btn btn-success pull-right" %>
		</h2><hr/>
			
		<div class="col-md-8 col-md-offset-2">	
			<table class="table borderless">
				<tr>
					 <b>
					 	<th class="sno">S.no</th>
						<th class="category">Category</th>
						<th class="available_books">Available Books</th>
					 </b>
				</tr>
				<% @categories.each_with_index do |category,i| %>	
					<tr>
						<td class="sno"><%= i+1 %>.</td>	
						<td class="text-center category"><%= link_to category.name, category_path(category), class: "text-center title" %></td>
						<td class="available_books"><%= category.books.count %></td>
					</tr>
				<% end %>		
			</table>
		</div>		
	</div>	
	<div class="container text-center">
		<div class="pagination">
			<%= paginate @categories %>
		</div>	
	</div>	
</div>	

app/views/categories/new.html.erb
<div class="container container1">	
	<div class="container">
		<h2>Adding Book <%= link_to "Back", categories_path(@category,@book), class: "btn btn-success pull-right" %></h2><hr/>
		<div class="col-md-8 col-md-offset-2">
			<%= render "form" %>
		</div>
	</div>
</div>	

app/views/categories/show.html.erb
<div class="container container1">
	<div class="container text-center">	
	<% if user_signed_in? %>
		<% if @user.books.count > 4 %>
			<% if @user.role != "admin" %>
				<b class="alert " style="color:red">To take another book, you have to submit already taken books.</b>
			<% end %>
		<% end %>
	<% end %>			
	</div>
	<div class="container">
		<h2> Show Page 
			<%= link_to "Categories", categories_path, class: "btn btn-success pull-right" %>
			<%= link_to "books", books_path, class: "btn btn-success pull-right" %>
			<% if user_signed_in? %>
				<% if @user.role == "admin" %>		
					<%= link_to "Delete", category_path(@category), method: :delete, data: { confirm: " Are you sure want to delete? " }, class: "btn btn-success pull-right" %>
					<%= link_to "Edit", edit_category_path(@category), class: "btn btn-success pull-right" %>
				<% end %>
			<% end %>		
		</h2><hr/>
		
		<div class="col-md-8 col-md-offset-2">
			<h2 class="text-center" ><u><b><%= @category.name %></b></u></h2>
			<p><h3><b>Available books:</b></h3></p><hr/>
			<% @category.books.each_with_index do |book,i| %>
				<p>
					<%= i+1 %>.
				    <%= link_to book.title, category_book_path(@category,book) %>			
					<% if user_signed_in? %>
						<% if @user.books.count <= 4 %>
							<% if @user.role != "admin" %>			
								<% if book.present_available_books > 0  %>
									<% if book.user_books.where(user_id: @user.id).present? %>
										<%= link_to "Booked", books_path, class: "btn btn-danger pull-right"  %>
									<% else %>	
										<%= link_to "Add Book", user_book_path(@user,book), method: :put, class: "btn btn-success pull-right"  %>
									<% end %>
								<% else %>
									<%= link_to "Booked", books_path, class: "btn btn-danger pull-right"  %>
								<% end %>
							<% end %>	
						<% end %>		
					<% end %>	
				</p><hr/>
			<% end %>	
		</div>
	</div>		
	<div class="container text-center">
		<div class="pagination">
			<%= paginate @category_books %>
		</div>	
	</div>
</div>	

app/views/layouts/admin.html.erb
<b>Admin</b>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibraryManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">	
	<div class="container">
		<div class="navbar-header">
			<%= link_to "Book categories", categories_path, class: "navbar-brand" %>
		</div>
		<ul class="nav navbar-nav pull-right">
			<% if !user_signed_in? %>
				<li><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default" %></li>
			<% end %>
			<% if user_signed_in? %>
				<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn-default" %></li>
			<% else %>
				<li><%= link_to "Sign In", new_user_session_path, class: "btn btn-default" %></li>	
			<% end %>	
		</ul>
	</div>	
</nav>	
<div class="container">	
	<% if user_signed_in? %>
		<b class="current-user pull-right">User:<u><%= current_user.email %></u></b>
	<% end %>
	<p class="notice  text-center"><%= notice %></p>
	<p class="alert  text-center"><%= alert %></p>
</div>
<%= yield %>

</body>
</html>

app/views/layouts/user.html.erb
<b>User</b>